# Generated by Django 5.1.5 on 2025-05-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aboutitem',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
